conky.config = {
  alignment = 'top_right', gap_x = 34, gap_y = 74,
  minimum_width = 265, maximum_width = 265,
  own_window = true, own_window_type = 'desktop', own_window_transparent = true,
  own_window_argb_visual = true, own_window_argb_value = 0,
  double_buffer = true, update_interval = 2,
  use_xft = true, font = 'Noto Sans:size=10',
  default_color = 'AAB8D8', color1 = '4CE7FF', color2 = 'A66CFF', color3 = '7DF9C9',
  draw_shades = false, draw_outline = false, uppercase = false,
};
conky.text = [[
${color1}${font Noto Sans:bold:size=12}LUNA TELEMETRY${font}${color}
${color2}${hr 2}${color}
${voffset 10}${font Noto Sans:bold:size=26}${time %H:%M}${font}
${color}${time %Y.%m.%d  %A}

${color1}CORE${alignr}${color3}${cpu cpu0}%
${color #28375f}${cpubar 7}${color}
${color1}MEMORY${alignr}${color3}${memperc}%
${color #28375f}${membar 7}${color}
${color1}STORAGE${alignr}${color3}${fs_used_perc /}%
${color #28375f}${fs_bar 7 /}${color}

${color2}●${color} SYSTEM ONLINE
${color #7184ad}MoonOS 0.1 Future // Luna Core
]];
